### ISSUE TITLE
Streamline GUI code to make it run faster on RPi

### ISSUE THREAD

**Issue by billyen33** [ESW-NU/AutoAquaponics#43]
Streamline GUI code to decrease the total lines of code and make it run faster on the Raspberry Pi. Right now there is a significant delay after pressing each button due to unknown reasons.

**Comment by christian-ctrl** [comment]
Streamlining is a continuous effort of mine, but prototype 2.0 lags significantly less than 1.0 from cumulative efforts. Issue closed because it's just a constant goal.
