### ISSUE TITLE
Label text cut off in Settings page

### ISSUE THREAD

**Issue by billyen33** [ESW-NU/AutoAquaponics#45]
The label that reads "Max Water Temperature (Celsius)" and "Min Water Temperature (Celsius)" in the Settings page are cut off toward the beginning if GUI is ran on the RPi. Either shorten the label or reconfigure the grid so they are not cut off.
![image](https://user-images.githubusercontent.com/66648349/89686327-ce532800-d8c3-11ea-9399-d041171dc505.png)

**Comment by christian-ctrl** [comment]
Ben C. fixed this by shortening the length of the label's string, as well as Bill's addition of the degree symbol to represent units in degrees Celsius.
