### ISSUE TITLE
Integrate sendtext.py into main code

### ISSUE THREAD

**Issue by billyen33** [ESW-NU/AutoAquaponics#49]
Integrate the texting message into main.py and GUI.py by doing the following:
1. Edit GUI.py/main.py so when the data read by DataLogger.py exceeds their respective specified boundary from Settings, the user gets a warning message from sendtext.py that tells them (1) which parameter is out of bound,(2) the time stamp of when that "bad" parameter was detected and (3) the detected value and the specified boundary values.
2. Add a place (maybe popup window to save space) for the user to input their (1) phone number and (2) cell phone service provider into entry widgets in Settings and be able to save that info into a SQLite table so sendtext.py knows where to send the warning messages.

**Comment by billyen33** [comment]
Add-on to this issue: Google automatically turns off access to less secure apps if you don't use them, so our popup message will get disabled by Google if it's not used frequently enough (not sure what the frequency is). Find a workaround to this to ensure that we really do send a message when we need to.

**Comment by billyen33** [comment]
@danielpetikian1 Really nice first version! It's definitely functional, and the message reflects exactly what we need it to. A couple things to fix:
1. Degree signs getting messed up on certain provider (AT&T is one, maybe there are more)
2. The air temperature message is cut off for AT&T
3. It sends 1 message every ~2 seconds when something is wrong, which causes the program to lag and the user to get an incredibly huge number of texts. I'm not sure what the best approach to solving this is (maybe only send the message once? or create a limit for how many messages you can send per hour for the same parameter?) but we need to fix this.

**Comment by christian-ctrl** [comment]
- Christian is trying to implement the Enable/Disable feature using a global variable and a checkbutton on the settings page.
- A limit in message frequency as well as the ability to function without the GUI being open (but data being logged) raises interesting challenges.
- Entering of phone number and service provider still needed on settings page and will need all instances of intializing and writing over the csv to account for a change in row 0.
