### ISSUE TITLE
Update the ReadMe file?

### ISSUE THREAD

**Issue by christian-ctrl** [ESW-NU/AutoAquaponics#54]
Hasn't been updated in a hot minute and our prototype has made progress :)

**Comment by billyen33** [comment]
Good idea, we really need to update the README haha

**Comment by billyen33** [comment]
Updated to reflect progress as of 12/7/2020, future updates will be needed especially when the warning message functionality is completed and the entry boxes for the users' phone numbers is fleshed out.
